image:
  file: .gitpod.yml

tasks:
  - command: sudo docker-up
    name: Docker daemon
  - name: Setup workspace
    command: bash setup.sh

vscode:
  extensions:
    - ms-azuretools.vscode-docker@1.8.1:xuHtLS23Q5czFwYH7grcCQ==

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
